services:
  - type: web
    name: zebrasync
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn zebrasync.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: zebrasync.onrender.com
